import { ClockCircleOutlined } from '@ant-design/icons';
import { Timeline } from 'antd';
import React from 'react'

const RightTimeline = () => {
  return (
    <Timeline
    items={[
        {
        children: 'Quotation Q0-1111 created by user 1',
        },
        {
        children: 'Sales order SO-1111 created by user 1',
        },
        {
        color: 'gray',
        children: 'Pick List for SO-1111 assigned to user 2',
        },
        {
        children: 'Delivery Challan DC-1111 generated by user 4',
        },
        {
        children: 'Delivery Challan DC-1111 delivered succesfully',
        },
    ]}
    />
  )
}
export default RightTimeline